import React from "react";
 //export const   CMS_URL = "https://edoctry-admin-production.up.railway.app";
//  export const CMS_URL = "https://edoctry.adaptable.app/api/";
//  export const UI_URL = "https://edoctry.com/";
//  export const jsonPageData = [
//     {
//       id: "tab-1",
//       ttl: "Courses",
//       slug: "basic",
//     },
//     {
//       id: "tab-2",
//       ttl: "Payment History",
//       slug: "photo",
//     },
//     {
//       id: "tab-3",
//       ttl: "Profile",
//       slug: "basic",
//     },
//     {
//       id: "tab-4",
//       ttl: "Photo",
//       slug: "photo",
//     },
//     {
//       id: "tab-5",
//       ttl: "Privacy Settings",
//       slug: "privacy",
//     },
//   ];
//  export const jsonPaymentHistory = [
//     {
//         id:1,
//         title:"All",
//         slug:"All"
//      },
//      {
//         id:2,
//         title:"Select Course",
//         slug:"All"
//      }
//  ]


//  export const textConst = {
//     register : "Successfully register! ",
//     LoginSuccess: "Logged in successfully!",
//     invalidData : "Invalid ",
//     testSubmit : "Successfully submitted your Answer!",
//     videoUploadSuccess : "Video uploaded successfully",
//     logoUploadSuccess:"Course Logo uploaded successfully",
//     uploadFailed:" uploading failed!",
//     EnterField: "Please Enter Field ",
//     enterMandatoryField:"Please Enter All Mandatory field!",
//     tableCreatedSuccess:"created successfully",
//     tableUpdatedSuccess:"Updated SuccessFully",
//     tableDeletedSuccess:"Deleted SuccessFully",
//     ForgotPassword:"Email sent to your register email, please verify your email",
//     newPasswordUpdate:"Your password does't match!",
//     passwordSuccess:"Password updated successfully",
//     addToCart:"Course Added to cart",
//     edoctryBusiness: "Your request submitted successfully",
//     userUnBlockSuccess: "An email has been successfully sent to your address. Please activate your user ID by following the instructions in the email.",
    
//  }

//  export const countryJson = [
//   {"txt": "Afghanistan", "value": "AF"},
//   {"txt": "Albania", "value": "AL"},
//   {"txt": "Algeria", "value": "DZ"},
//   {"txt": "Andorra", "value": "AD"},
//   {"txt": "Angola", "value": "AO"},
//   {"txt": "Antigua and Barbuda", "value": "AG"},
//   {"txt": "Argentina", "value": "AR"},
//   {"txt": "Armenia", "value": "AM"},
//   {"txt": "Australia", "value": "AU"},
//   {"txt": "Austria", "value": "AT"},
//   {"txt": "Azerbaijan", "value": "AZ"},
//   {"txt": "Bahamas", "value": "BS"},
//   {"txt": "Bahrain", "value": "BH"},
//   {"txt": "Bangladesh", "value": "BD"},
//   {"txt": "Barbados", "value": "BB"},
//   {"txt": "Belarus", "value": "BY"},
//   {"txt": "Belgium", "value": "BE"},
//   {"txt": "Belize", "value": "BZ"},
//   {"txt": "Benin", "value": "BJ"},
//   {"txt": "Bhutan", "value": "BT"},
//   {"txt": "Bolivia", "value": "BO"},
//   {"txt": "Bosnia and Herzegovina", "value": "BA"},
//   {"txt": "Botswana", "value": "BW"},
//   {"txt": "Brazil", "value": "BR"},
//   {"txt": "Brunei Darussalam", "value": "BN"},
//   {"txt": "Bulgaria", "value": "BG"},
//   {"txt": "Burkina Faso", "value": "BF"},
//   {"txt": "Burundi", "value": "BI"},
//   {"txt": "Cabo Verde", "value": "CV"},
//   {"txt": "Cambodia", "value": "KH"},
//   {"txt": "Cameroon", "value": "CM"},
//   {"txt": "Canada", "value": "CA"},
//   {"txt": "Central African Republic", "value": "CF"},
//   {"txt": "Chad", "value": "TD"},
//   {"txt": "Chile", "value": "CL"},
//   {"txt": "China", "value": "CN"},
//   {"txt": "Colombia", "value": "CO"},
//   {"txt": "Comoros", "value": "KM"},
//   {"txt": "Congo", "value": "CG"},
//   {"txt": "Costa Rica", "value": "CR"},
//   {"txt": "Croatia", "value": "HR"},
//   {"txt": "Cuba", "value": "CU"},
//   {"txt": "Cyprus", "value": "CY"},
//   {"txt": "Czech Republic", "value": "CZ"},
//   {"txt": "Denmark", "value": "DK"},
//   {"txt": "Djibouti", "value": "DJ"},
//   {"txt": "Dominica", "value": "DM"},
//   {"txt": "Dominican Republic", "value": "DO"},
//   {"txt": "Ecuador", "value": "EC"},
//   {"txt": "Egypt", "value": "EG"},
//   {"txt": "El Salvador", "value": "SV"},
//   {"txt": "Equatorial Guinea", "value": "GQ"},
//   {"txt": "Eritrea", "value": "ER"},
//   {"txt": "Estonia", "value": "EE"},
//   {"txt": "Eswatini", "value": "SZ"},
//   {"txt": "Ethiopia", "value": "ET"},
//   {"txt": "Fiji", "value": "FJ"},
//   {"txt": "Finland", "value": "FI"},
//   {"txt": "France", "value": "FR"},
//   {"txt": "Gabon", "value": "GA"},
//   {"txt": "Gambia", "value": "GM"},
//   {"txt": "Georgia", "value": "GE"},
//   {"txt": "Germany", "value": "DE"},
//   {"txt": "Ghana", "value": "GH"},
//   {"txt": "Greece", "value": "GR"},
//   {"txt": "Grenada", "value": "GD"},
//   {"txt": "Guatemala", "value": "GT"},
//   {"txt": "Guinea", "value": "GN"},
//   {"txt": "Guinea-Bissau", "value": "GW"},
//   {"txt": "Guyana", "value": "GY"},
//   {"txt": "Haiti", "value": "HT"},
//   {"txt": "Honduras", "value": "HN"},
//   {"txt": "Hungary", "value": "HU"},
//   {"txt": "Iceland", "value": "IS"},
//   {"txt": "India", "value": "IN"},
//   {"txt": "Indonesia", "value": "ID"},
//   {"txt": "Iran", "value": "IR"},
//   {"txt": "Iraq", "value": "IQ"},
//   {"txt": "Ireland", "value": "IE"},
//   {"txt": "Israel", "value": "IL"},
//   {"txt": "Italy", "value": "IT"},
//   {"txt": "Jamaica", "value": "JM"},
//   {"txt": "Japan", "value": "JP"},
//   {"txt": "Jordan", "value": "JO"},
//   {"txt": "Kazakhstan", "value": "KZ"},
//   {"txt": "Kenya", "value": "KE"},
//   {"txt": "Kiribati", "value": "KI"},
//   {"txt": "Korea, Democratic People's Republic of", "value": "KP"},
//   {"txt": "Korea, Republic of", "value": "KR"},
//   {"txt": "Kuwait", "value": "KW"},
//   {"txt": "Kyrgyzstan", "value": "KG"},
//   {"txt": "Lao People's Democratic Republic", "value": "LA"},
//   {"txt": "Latvia", "value": "LV"},
//   {"txt": "Lebanon", "value": "LB"},
//   {"txt": "Lesotho", "value": "LS"},
//   {"txt": "Liberia", "value": "LR"},
//   {"txt": "Libya", "value": "LY"},
//   {"txt": "Liechtenstein", "value": "LI"},
//   {"txt": "Lithuania", "value": "LT"},
//   {"txt": "Luxembourg", "value": "LU"},
//   {"txt": "Madagascar", "value": "MG"},
//   {"txt": "Malawi", "value": "MW"},
//   {"txt": "Malaysia", "value": "MY"},
//   {"txt": "Maldives", "value": "MV"},
//   {"txt": "Mali", "value": "ML"},
//   {"txt": "Malta", "value": "MT"},
//   {"txt": "Marshall Islands", "value": "MH"},
//   {"txt": "Mauritania", "value": "MR"},
//   {"txt": "Mauritius", "value": "MU"},
//   {"txt": "Mexico", "value": "MX"},
//   {"txt": "Micronesia", "value": "FM"},
//   {"txt": "Moldova", "value": "MD"},
//   {"txt": "Monaco", "value": "MC"},
//   {"txt": "Mongolia", "value": "MN"},
//   {"txt": "Montenegro", "value": "ME"},
//   {"txt": "Morocco", "value": "MA"},
//   {"txt": "Mozambique", "value": "MZ"},
//   {"txt": "Myanmar", "value": "MM"},
//   {"txt": "Namibia", "value": "NA"},
//   {"txt": "Nauru", "value": "NR"},
//   {"txt": "Nepal", "value": "NP"},
//   {"txt": "Netherlands", "value": "NL"},
//   {"txt": "New Zealand", "value": "NZ"},
//   {"txt": "Nicaragua", "value": "NI"},
//   {"txt": "Niger", "value": "NE"},
//   {"txt": "Nigeria", "value": "NG"},
//   {"txt": "North Macedonia", "value": "MK"},
//   {"txt": "Norway", "value": "NO"},
//   {"txt": "Oman", "value": "OM"},
//   {"txt": "Pakistan", "value": "PK"},
//   {"txt": "Palau", "value": "PW"},
//   {"txt": "Panama", "value": "PA"},
//   {"txt": "Papua New Guinea", "value": "PG"},
//   {"txt": "Paraguay", "value": "PY"},
//   {"txt": "Peru", "value": "PE"},
//   {"txt": "Philippines", "value": "PH"},
//   {"txt": "Poland", "value": "PL"},
//   {"txt": "Portugal", "value": "PT"},
//   {"txt": "Qatar", "value": "QA"},
//   {"txt": "Romania", "value": "RO"},
//   {"txt": "Russian Federation", "value": "RU"},
//   {"txt": "Rwanda", "value": "RW"},
//   {"txt": "Saint Kitts and Nevis", "value": "KN"},
//   {"txt": "Saint Lucia", "value": "LC"},
//   {"txt": "Saint Vincent and the Grenadines", "value": "VC"},
//   {"txt": "Samoa", "value": "WS"},
//   {"txt": "San Marino", "value": "SM"},
//   {"txt": "Sao Tome and Principe", "value": "ST"},
//   {"txt": "Saudi Arabia", "value": "SA"},
//   {"txt": "Senegal", "value": "SN"},
//   {"txt": "Serbia", "value": "RS"},
//   {"txt": "Seychelles", "value": "SC"},
//   {"txt": "Sierra Leone", "value": "SL"},
//   {"txt": "Singapore", "value": "SG"},
//   {"txt": "Slovakia", "value": "SK"},
//   {"txt": "Slovenia", "value": "SI"},
//   {"txt": "Solomon Islands", "value": "SB"},
//   {"txt": "Somalia", "value": "SO"},
//   {"txt": "South Africa", "value": "ZA"},
//   {"txt": "South Sudan", "value": "SS"},
//   {"txt": "Spain", "value": "ES"},
//   {"txt": "Sri Lanka", "value": "LK"},
//   {"txt": "Sudan", "value": "SD"},
//   {"txt": "Suriname", "value": "SR"},
//   {"txt": "Sweden", "value": "SE"},
//   {"txt": "Switzerland", "value": "CH"},
//   {"txt": "Syrian Arab Republic", "value": "SY"},
//   {"txt": "Tajikistan", "value": "TJ"},
//   {"txt": "Tanzania", "value": "TZ"},
//   {"txt": "Thailand", "value": "TH"},
//   {"txt": "Timor-Leste", "value": "TL"},
//   {"txt": "Togo", "value": "TG"},
//   {"txt": "Tonga", "value": "TO"},
//   {"txt": "Trinidad and Tobago", "value": "TT"},
//   {"txt": "Tunisia", "value": "TN"},
//   {"txt": "Turkey", "value": "TR"},
//   {"txt": "Turkmenistan", "value": "TM"},
//   {"txt": "Tuvalu", "value": "TV"},
//   {"txt": "Uganda", "value": "UG"},
//   {"txt": "Ukraine", "value": "UA"},
//   {"txt": "United Arab Emirates", "value": "AE"},
//   {"txt": "United Kingdom of Great Britain and Northern Ireland", "value": "GB"},
//   {"txt": "United States of America", "value": "US"},
//   {"txt": "Uruguay", "value": "UY"},
//   {"txt": "Uzbekistan", "value": "UZ"},
//   {"txt": "Vanuatu", "value": "VU"},
//   {"txt": "Venezuela", "value": "VE"},
//   {"txt": "Viet Nam", "value": "VN"},
//   {"txt": "Yemen", "value": "YE"},
//   {"txt": "Zambia", "value": "ZM"},
//   {"txt": "Zimbabwe", "value": "ZW"}
// ]

const ConstData = {
  CMS_URL : "http://api.edoctry.com/api/",
  UI_URL : "https://edoctry.com/",
  jsonPageData : [
    {
      id: "tab-1",
      ttl: "Courses",
      slug: "basic",
    },
    {
      id: "tab-2",
      ttl: "Payment History",
      slug: "photo",
    },
    {
      id: "tab-3",
      ttl: "Profile",
      slug: "basic",
    },
    {
      id: "tab-4",
      ttl: "Photo",
      slug: "photo",
    },
    {
      id: "tab-5",
      ttl: "Privacy Settings",
      slug: "privacy",
    },
  ],
  jsonPaymentHistory : [
    {
        id:1,
        title:"All",
        slug:"All"
     },
     {
        id:2,
        title:"Select Course",
        slug:"All"
     }
 ],
 textConst : {
  register : "Successfully register! ",
  LoginSuccess: "Logged in successfully!",
  invalidData : "Invalid ",
  testSubmit : "Successfully submitted your Answer!",
  videoUploadSuccess : "Video uploaded successfully",
  logoUploadSuccess:"Course Logo uploaded successfully",
  uploadFailed:" uploading failed!",
  EnterField: "Please Enter Field ",
  enterMandatoryField:"Please Enter All Mandatory field!",
  tableCreatedSuccess:"created successfully",
  tableUpdatedSuccess:"Updated SuccessFully",
  tableDeletedSuccess:"Deleted SuccessFully",
  ForgotPassword:"Email sent to your register email, please verify your email",
  newPasswordUpdate:"Your password does't match!",
  passwordSuccess:"Password updated successfully",
  addToCart:"Course Added to cart",
  edoctryBusiness: "Your request submitted successfully",
  userUnBlockSuccess: "An email has been successfully sent to your address. Please activate your user ID by following the instructions in the email.",
  
},
countryJson : [
  {"txt": "Afghanistan", "value": "AF"},
  {"txt": "Albania", "value": "AL"},
  {"txt": "Algeria", "value": "DZ"},
  {"txt": "Andorra", "value": "AD"},
  {"txt": "Angola", "value": "AO"},
  {"txt": "Antigua and Barbuda", "value": "AG"},
  {"txt": "Argentina", "value": "AR"},
  {"txt": "Armenia", "value": "AM"},
  {"txt": "Australia", "value": "AU"},
  {"txt": "Austria", "value": "AT"},
  {"txt": "Azerbaijan", "value": "AZ"},
  {"txt": "Bahamas", "value": "BS"},
  {"txt": "Bahrain", "value": "BH"},
  {"txt": "Bangladesh", "value": "BD"},
  {"txt": "Barbados", "value": "BB"},
  {"txt": "Belarus", "value": "BY"},
  {"txt": "Belgium", "value": "BE"},
  {"txt": "Belize", "value": "BZ"},
  {"txt": "Benin", "value": "BJ"},
  {"txt": "Bhutan", "value": "BT"},
  {"txt": "Bolivia", "value": "BO"},
  {"txt": "Bosnia and Herzegovina", "value": "BA"},
  {"txt": "Botswana", "value": "BW"},
  {"txt": "Brazil", "value": "BR"},
  {"txt": "Brunei Darussalam", "value": "BN"},
  {"txt": "Bulgaria", "value": "BG"},
  {"txt": "Burkina Faso", "value": "BF"},
  {"txt": "Burundi", "value": "BI"},
  {"txt": "Cabo Verde", "value": "CV"},
  {"txt": "Cambodia", "value": "KH"},
  {"txt": "Cameroon", "value": "CM"},
  {"txt": "Canada", "value": "CA"},
  {"txt": "Central African Republic", "value": "CF"},
  {"txt": "Chad", "value": "TD"},
  {"txt": "Chile", "value": "CL"},
  {"txt": "China", "value": "CN"},
  {"txt": "Colombia", "value": "CO"},
  {"txt": "Comoros", "value": "KM"},
  {"txt": "Congo", "value": "CG"},
  {"txt": "Costa Rica", "value": "CR"},
  {"txt": "Croatia", "value": "HR"},
  {"txt": "Cuba", "value": "CU"},
  {"txt": "Cyprus", "value": "CY"},
  {"txt": "Czech Republic", "value": "CZ"},
  {"txt": "Denmark", "value": "DK"},
  {"txt": "Djibouti", "value": "DJ"},
  {"txt": "Dominica", "value": "DM"},
  {"txt": "Dominican Republic", "value": "DO"},
  {"txt": "Ecuador", "value": "EC"},
  {"txt": "Egypt", "value": "EG"},
  {"txt": "El Salvador", "value": "SV"},
  {"txt": "Equatorial Guinea", "value": "GQ"},
  {"txt": "Eritrea", "value": "ER"},
  {"txt": "Estonia", "value": "EE"},
  {"txt": "Eswatini", "value": "SZ"},
  {"txt": "Ethiopia", "value": "ET"},
  {"txt": "Fiji", "value": "FJ"},
  {"txt": "Finland", "value": "FI"},
  {"txt": "France", "value": "FR"},
  {"txt": "Gabon", "value": "GA"},
  {"txt": "Gambia", "value": "GM"},
  {"txt": "Georgia", "value": "GE"},
  {"txt": "Germany", "value": "DE"},
  {"txt": "Ghana", "value": "GH"},
  {"txt": "Greece", "value": "GR"},
  {"txt": "Grenada", "value": "GD"},
  {"txt": "Guatemala", "value": "GT"},
  {"txt": "Guinea", "value": "GN"},
  {"txt": "Guinea-Bissau", "value": "GW"},
  {"txt": "Guyana", "value": "GY"},
  {"txt": "Haiti", "value": "HT"},
  {"txt": "Honduras", "value": "HN"},
  {"txt": "Hungary", "value": "HU"},
  {"txt": "Iceland", "value": "IS"},
  {"txt": "India", "value": "IN"},
  {"txt": "Indonesia", "value": "ID"},
  {"txt": "Iran", "value": "IR"},
  {"txt": "Iraq", "value": "IQ"},
  {"txt": "Ireland", "value": "IE"},
  {"txt": "Israel", "value": "IL"},
  {"txt": "Italy", "value": "IT"},
  {"txt": "Jamaica", "value": "JM"},
  {"txt": "Japan", "value": "JP"},
  {"txt": "Jordan", "value": "JO"},
  {"txt": "Kazakhstan", "value": "KZ"},
  {"txt": "Kenya", "value": "KE"},
  {"txt": "Kiribati", "value": "KI"},
  {"txt": "Korea, Democratic People's Republic of", "value": "KP"},
  {"txt": "Korea, Republic of", "value": "KR"},
  {"txt": "Kuwait", "value": "KW"},
  {"txt": "Kyrgyzstan", "value": "KG"},
  {"txt": "Lao People's Democratic Republic", "value": "LA"},
  {"txt": "Latvia", "value": "LV"},
  {"txt": "Lebanon", "value": "LB"},
  {"txt": "Lesotho", "value": "LS"},
  {"txt": "Liberia", "value": "LR"},
  {"txt": "Libya", "value": "LY"},
  {"txt": "Liechtenstein", "value": "LI"},
  {"txt": "Lithuania", "value": "LT"},
  {"txt": "Luxembourg", "value": "LU"},
  {"txt": "Madagascar", "value": "MG"},
  {"txt": "Malawi", "value": "MW"},
  {"txt": "Malaysia", "value": "MY"},
  {"txt": "Maldives", "value": "MV"},
  {"txt": "Mali", "value": "ML"},
  {"txt": "Malta", "value": "MT"},
  {"txt": "Marshall Islands", "value": "MH"},
  {"txt": "Mauritania", "value": "MR"},
  {"txt": "Mauritius", "value": "MU"},
  {"txt": "Mexico", "value": "MX"},
  {"txt": "Micronesia", "value": "FM"},
  {"txt": "Moldova", "value": "MD"},
  {"txt": "Monaco", "value": "MC"},
  {"txt": "Mongolia", "value": "MN"},
  {"txt": "Montenegro", "value": "ME"},
  {"txt": "Morocco", "value": "MA"},
  {"txt": "Mozambique", "value": "MZ"},
  {"txt": "Myanmar", "value": "MM"},
  {"txt": "Namibia", "value": "NA"},
  {"txt": "Nauru", "value": "NR"},
  {"txt": "Nepal", "value": "NP"},
  {"txt": "Netherlands", "value": "NL"},
  {"txt": "New Zealand", "value": "NZ"},
  {"txt": "Nicaragua", "value": "NI"},
  {"txt": "Niger", "value": "NE"},
  {"txt": "Nigeria", "value": "NG"},
  {"txt": "North Macedonia", "value": "MK"},
  {"txt": "Norway", "value": "NO"},
  {"txt": "Oman", "value": "OM"},
  {"txt": "Pakistan", "value": "PK"},
  {"txt": "Palau", "value": "PW"},
  {"txt": "Panama", "value": "PA"},
  {"txt": "Papua New Guinea", "value": "PG"},
  {"txt": "Paraguay", "value": "PY"},
  {"txt": "Peru", "value": "PE"},
  {"txt": "Philippines", "value": "PH"},
  {"txt": "Poland", "value": "PL"},
  {"txt": "Portugal", "value": "PT"},
  {"txt": "Qatar", "value": "QA"},
  {"txt": "Romania", "value": "RO"},
  {"txt": "Russian Federation", "value": "RU"},
  {"txt": "Rwanda", "value": "RW"},
  {"txt": "Saint Kitts and Nevis", "value": "KN"},
  {"txt": "Saint Lucia", "value": "LC"},
  {"txt": "Saint Vincent and the Grenadines", "value": "VC"},
  {"txt": "Samoa", "value": "WS"},
  {"txt": "San Marino", "value": "SM"},
  {"txt": "Sao Tome and Principe", "value": "ST"},
  {"txt": "Saudi Arabia", "value": "SA"},
  {"txt": "Senegal", "value": "SN"},
  {"txt": "Serbia", "value": "RS"},
  {"txt": "Seychelles", "value": "SC"},
  {"txt": "Sierra Leone", "value": "SL"},
  {"txt": "Singapore", "value": "SG"},
  {"txt": "Slovakia", "value": "SK"},
  {"txt": "Slovenia", "value": "SI"},
  {"txt": "Solomon Islands", "value": "SB"},
  {"txt": "Somalia", "value": "SO"},
  {"txt": "South Africa", "value": "ZA"},
  {"txt": "South Sudan", "value": "SS"},
  {"txt": "Spain", "value": "ES"},
  {"txt": "Sri Lanka", "value": "LK"},
  {"txt": "Sudan", "value": "SD"},
  {"txt": "Suriname", "value": "SR"},
  {"txt": "Sweden", "value": "SE"},
  {"txt": "Switzerland", "value": "CH"},
  {"txt": "Syrian Arab Republic", "value": "SY"},
  {"txt": "Tajikistan", "value": "TJ"},
  {"txt": "Tanzania", "value": "TZ"},
  {"txt": "Thailand", "value": "TH"},
  {"txt": "Timor-Leste", "value": "TL"},
  {"txt": "Togo", "value": "TG"},
  {"txt": "Tonga", "value": "TO"},
  {"txt": "Trinidad and Tobago", "value": "TT"},
  {"txt": "Tunisia", "value": "TN"},
  {"txt": "Turkey", "value": "TR"},
  {"txt": "Turkmenistan", "value": "TM"},
  {"txt": "Tuvalu", "value": "TV"},
  {"txt": "Uganda", "value": "UG"},
  {"txt": "Ukraine", "value": "UA"},
  {"txt": "United Arab Emirates", "value": "AE"},
  {"txt": "United Kingdom of Great Britain and Northern Ireland", "value": "GB"},
  {"txt": "United States of America", "value": "US"},
  {"txt": "Uruguay", "value": "UY"},
  {"txt": "Uzbekistan", "value": "UZ"},
  {"txt": "Vanuatu", "value": "VU"},
  {"txt": "Venezuela", "value": "VE"},
  {"txt": "Viet Nam", "value": "VN"},
  {"txt": "Yemen", "value": "YE"},
  {"txt": "Zambia", "value": "ZM"},
  {"txt": "Zimbabwe", "value": "ZW"}
]


}
export default ConstData; 




